---
title: "EDA"
author: "Lily Zhu"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
library(tidyverse)
```

```{r}
us_19 <- read_csv('~/df_data/US/us_19.csv')
#glimpse(us_19)
```

```{r}
us_19 %>% 
  mutate(THC_USE = as.factor(THC_USE), DAST_1 = as.factor(DAST_1)) %>% 
  ggplot(mapping = aes(x = DAST_1, fill = THC_USE)) +
  geom_bar() + 
  scale_fill_brewer(palette="Set3")
```

```{r}
us_19 %>%
  group_by(factor(DAST_1)) %>% 
  count(factor(THC_USE)) %>% 
  mutate(pct_total = n/sum(n))
```

```{r}
ggplot(data = us_19, mapping = aes(x = as.factor(DAST_CAT), fill = as.factor(THC_USE))) +
  geom_bar(position = "fill") + 
  labs(title = "Relationship between DAST-10 category \nand prescription cannabinoid lifetime use", 
       x = "DAST-10 category", 
       y = "Count") +
  scale_fill_discrete(name = "Prescription cannabinoid \nlifetime use", labels = c("No", "Yes"), guide = guide_legend(reverse=TRUE))
```

```{r}
us_19_mod <- us_19 %>% 
  select(starts_with("THC"), starts_with("DEM"), DAST_CAT) %>% 
  subset(select = -c(DEM_PREG, DEM_PREG_WK, DEM_STDNT_PROGRAM, DEM_STDNT_UNDER, DEM_VET_SERV, DEM_HEALTH_PRIV, DEM_HEALTH_PRE, DEM_HEALTH_HOS, DEM_HEALTH_OUT, DEM_HEALTH_HOME, DEM_HEALTH_OTH, DEM_HEALTH_ROLE))
glimpse(us_19_mod)
```

```{r}
us_19 %>% 
     select(starts_with("DEM"))
```

```{r full model, results = "hide"}
full_model <- multinom(DAST_CAT ~ ., 
                       data = us_19_mod)
```

```{r tidy full model}
tidy(full_model) %>%
  kable(digits = 3)
```

```{r backward model selection, results = "hide"}
int_only_model <- multinom(DAST_CAT ~ 1, data = us_19_mod)

final_model <- step(full_model, scope = formula(int_only_model), direction = "backward")
```

```{r tidy final model}
tidy(final_model, conf.int = TRUE) %>% 
  kable(digits = 3)
```